import Head from 'next/head';
import { getSession } from 'next-auth/react';
import { GetServerSideProps } from 'next/types';
import EditUserForm from '@/components/usereditform';
import { Title } from '@/components/title';

export default function EditUserPage() {
  return (
    <>
      <Head>
        <title>Edit User</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Title>Edit User</Title>
      <div className='dashboard-container'>
        <EditUserForm />
      </div>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession({ req: context.req });

  if (!session) {
    return {
      redirect: {
        destination: '/',
        permanent: false,
      },
    };
  }

  return {
    props: {
      session,
    },
  };
};
