import Head from 'next/head';
import { useQuery } from 'react-query';
import { getSession } from 'next-auth/react';
import { GetServerSideProps } from 'next/types';
import { Title } from '@/components/layout/Title';
import UserView from '@/components/data-display/UserView';

export type UserData = {
  id: string;
  admin: string;
  first: string;
  last: string;
  title: string;
  phone: string;
  inactive: boolean;
};

export type User = {
  id: string;
  admin: string;
  first: string;
  last: string;
  title: string;
  phone: string;
  inactive: string;
};

const fetchUserData = async () => {
  const res = await fetch('https://my-json-server.typicode.com/dmcleish91/demo/users');
  return await res.json();
};

export default function Management() {
  const { data, isLoading } = useQuery<UserData[]>('users', fetchUserData);

  if (isLoading) return null;

  let mappedData: User[] | undefined;

  if (data) {
    mappedData = data.map((user) => {
      return {
        ...user,
        inactive: user.inactive ? 'Inactive' : 'Active',
      };
    });

    console.log(mappedData);
  }

  return (
    <>
      <Head>
        <title>Management</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Title>User Management</Title>
      <div className='dashboard-container'>
        <UserView userData={mappedData} />
      </div>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession({ req: context.req });

  if (!session) {
    return {
      redirect: {
        destination: '/',
        permanent: false,
      },
    };
  }

  return {
    props: {
      session,
    },
  };
};
